# ========== PERMITIR DEPENDENCIAS CIRCULARES ==========
spring.main.allow-circular-references=true

# ========== SPRING ==========
spring.application.name=ingenieriaSoftware2

# ========== SERVER ==========
server.port=${PORT:8080}

# ========== DATABASE ==========
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:ingenieriaSoftware2;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console

# ========== HIKARICP POOL SETTINGS (SUPABASE POOLER / RENDER) ==========
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

# ========== JPA ==========
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========== SQL INIT ==========
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.continue-on-error=true

# ========== JWT ==========
jwt.secret=miClaveSecretaSuperSeguraParaJWTConMasDe32Caracteres
jwt.expiration=86400000

# ========== LOGGING ==========
logging.level.com.ingenieriaSoftware2=DEBUG
logging.level.org.springframework.security=DEBUG