import type { Book, User, TradeRequest, PointMovement, Review, TrackedBook, NotificationItem } from "./mercado-types"
import { calculateReferencePrice } from "./price-evaluator"

export const SEED_USERS: User[] = [
  {
    id: "user-1",
    name: "Franco Papa",
    username: "francopapa",
    email: "franco@mercadolibro.com",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
    bio: "Apasionado por la literatura latinoamericana y la divulgación científica.",
    city: "Buenos Aires, Argentina",
    rating: 4.9,
    totalReviews: 8,
    totalTrades: 9,
    availablePoints: 100,
    reservedPoints: 0,
    joinedDate: "2024-01-10T10:00:00.000Z",
  },
  {
    id: "user-2",
    name: "Miguel Bartesaghi",
    username: "miguelb",
    email: "miguel@mercadolibro.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250",
    bio: "Lector voraz de novelas históricas y clásicos universales. Cuido mucho mis libros.",
    city: "Córdoba, Argentina",
    rating: 4.8,
    totalReviews: 12,
    totalTrades: 14,
    availablePoints: 140,
    reservedPoints: 0,
    joinedDate: "2023-11-15T12:00:00.000Z",
  },
  {
    id: "user-3",
    name: "Camila García",
    username: "camigarcia",
    email: "camila@mercadolibro.com",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250",
    bio: "Estudiante de letras. Intercambio novelas contemporáneas, poesía y ensayos.",
    city: "Rosario, Argentina",
    rating: 4.95,
    totalReviews: 15,
    totalTrades: 16,
    availablePoints: 115,
    reservedPoints: 0,
    joinedDate: "2023-10-05T09:30:00.000Z",
  },
  {
    id: "user-4",
    name: "Juan Martín Berglavaz",
    username: "jmberglavaz",
    email: "juan@mercadolibro.com",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250",
    bio: "Desarrollador de software y fan de la ciencia ficción, manuales técnicos y cómics.",
    city: "La Plata, Argentina",
    rating: 5.0,
    totalReviews: 10,
    totalTrades: 11,
    availablePoints: 120,
    reservedPoints: 0,
    joinedDate: "2023-12-01T14:00:00.000Z",
  },
]

export const SEED_BOOKS: Book[] = [
  {
    id: "book-1",
    title: "Rayuela",
    author: "Julio Cortázar",
    isbn: "978-84-376-0457-2",
    category: "Ficción",
    condition: "Muy bueno",
    points: 50,
    edition: "Edición Cátedra Conmemorativa 2021",
    description: "Novela cumbre de la literatura en español con tablero de dirección intacto y páginas cuidadas.",
    coverUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-1",
    ownerName: "Franco Papa",
    ownerRating: 4.9,
    ownerTrades: 9,
    availability: "DISPONIBLE",
    externalRating: 4.7,
    referencePrice: 56,
    createdAt: "2024-02-01T10:00:00.000Z",
  },
  {
    id: "book-2",
    title: "Ficciones",
    author: "Jorge Luis Borges",
    isbn: "978-987-566-646-7",
    category: "Ficción",
    condition: "Como nuevo",
    points: 65,
    edition: "Debolsillo Clásica 2020",
    description: "Incluye El jardín de senderos que se bifurcan y Artificios. En excelente estado de conservación.",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-2",
    ownerName: "Miguel Bartesaghi",
    ownerRating: 4.8,
    ownerTrades: 14,
    availability: "DISPONIBLE",
    externalRating: 4.8,
    referencePrice: 73,
    createdAt: "2024-02-02T12:00:00.000Z",
  },
  {
    id: "book-3",
    title: "Sapiens: De animales a dioses",
    author: "Yuval Noah Harari",
    isbn: "978-84-9992-421-2",
    category: "No ficción",
    condition: "Nuevo",
    points: 80,
    edition: "Debate Tapa Dura 2022",
    description: "Breve historia de la humanidad. Sin uso, ejemplar impecable.",
    coverUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-3",
    ownerName: "Camila García",
    ownerRating: 4.95,
    ownerTrades: 16,
    availability: "DISPONIBLE",
    externalRating: 4.6,
    referencePrice: 87,
    createdAt: "2024-02-03T15:00:00.000Z",
  },
  {
    id: "book-4",
    title: "Clean Code: Manual de estilo ágil",
    author: "Robert C. Martin",
    isbn: "978-013-235088-4",
    category: "Técnico",
    condition: "Muy bueno",
    points: 70,
    edition: "Prentice Hall 2019",
    description: "Un clásico para desarrollo de software profesional. En encuadernación original.",
    coverUrl: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-4",
    ownerName: "Juan Martín Berglavaz",
    ownerRating: 5.0,
    ownerTrades: 11,
    availability: "DISPONIBLE",
    externalRating: 4.5,
    referencePrice: 77,
    createdAt: "2024-02-04T11:00:00.000Z",
  },
  {
    id: "book-5",
    title: "Una breve historia del tiempo",
    author: "Stephen Hawking",
    isbn: "978-84-9892-000-0",
    category: "Ciencia",
    condition: "Bueno",
    points: 40,
    edition: "Crítica 2018",
    description: "Del Big Bang a los agujeros negros. Tapa con leve desgaste en esquinas, interior perfecto.",
    coverUrl: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-2",
    ownerName: "Miguel Bartesaghi",
    ownerRating: 4.8,
    ownerTrades: 14,
    availability: "DISPONIBLE",
    externalRating: 4.4,
    referencePrice: 48,
    createdAt: "2024-02-05T09:00:00.000Z",
  },
  {
    id: "book-6",
    title: "El Aleph",
    author: "Jorge Luis Borges",
    isbn: "978-950-07-2856-0",
    category: "Ficción",
    condition: "Muy bueno",
    points: 48,
    edition: "Sudamericana 2017",
    description: "Colección de cuentos fundamentales. Incluye El inmortal y El Zahir.",
    coverUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-3",
    ownerName: "Camila García",
    ownerRating: 4.95,
    ownerTrades: 16,
    availability: "DISPONIBLE",
    externalRating: 4.8,
    referencePrice: 56,
    createdAt: "2024-02-06T14:30:00.000Z",
  },
  {
    id: "book-7",
    title: "Cien años de soledad",
    author: "Gabriel García Márquez",
    isbn: "978-84-204-7183-9",
    category: "Ficción",
    condition: "Como nuevo",
    points: 68,
    edition: "RAE Edición 50 Aniversario",
    description: "Edición conmemorativa con notas y árbol genealógico desplegable.",
    coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-4",
    ownerName: "Juan Martín Berglavaz",
    ownerRating: 5.0,
    ownerTrades: 11,
    availability: "DISPONIBLE",
    externalRating: 4.9,
    referencePrice: 74,
    createdAt: "2024-02-07T16:00:00.000Z",
  },
  {
    id: "book-8",
    title: "Cosmos",
    author: "Carl Sagan",
    isbn: "978-84-08-05307-1",
    category: "Ciencia",
    condition: "Como nuevo",
    points: 75,
    edition: "Planeta Ilustrada 2021",
    description: "La gran obra de divulgación científica con fotografías a color.",
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-1",
    ownerName: "Franco Papa",
    ownerRating: 4.9,
    ownerTrades: 9,
    availability: "DISPONIBLE",
    externalRating: 4.8,
    referencePrice: 87,
    createdAt: "2024-02-08T18:00:00.000Z",
  },
  {
    id: "book-9",
    title: "El principito",
    author: "Antoine de Saint-Exupéry",
    isbn: "978-987-612-456-1",
    category: "Infantil",
    condition: "Aceptable",
    points: 22,
    edition: "Emecé Bolsillo",
    description: "Clásico universal con acuarelas originales del autor. Tapas gastadas.",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-2",
    ownerName: "Miguel Bartesaghi",
    ownerRating: 4.8,
    ownerTrades: 14,
    availability: "DISPONIBLE",
    externalRating: 4.6,
    referencePrice: 26,
    createdAt: "2024-02-09T10:00:00.000Z",
  },
  {
    id: "book-10",
    title: "Mafalda: Todas las tiras",
    author: "Quino",
    isbn: "978-950-515-600-9",
    category: "Comics y novela gráfica",
    condition: "Muy bueno",
    points: 60,
    edition: "De la Flor Gran Formato 2018",
    description: "Tomo integral que recopila todas las tiras de Mafalda de 1964 a 1973.",
    coverUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=600",
    ownerId: "user-3",
    ownerName: "Camila García",
    ownerRating: 4.95,
    ownerTrades: 16,
    availability: "DISPONIBLE",
    externalRating: 4.9,
    referencePrice: 73,
    createdAt: "2024-02-10T11:20:00.000Z",
  },
]

export const SEED_REVIEWS: Review[] = [
  {
    id: "rev-1",
    tradeId: "tr-past-1",
    fromUserId: "user-2",
    fromUserName: "Miguel Bartesaghi",
    toUserId: "user-1",
    rating: 5,
    comment: "Excelente intercambio. El libro estaba impecable y la coordinación fue rápida y cordial.",
    date: "2024-01-20T16:00:00.000Z",
    bookTitle: "Rayuela",
  },
  {
    id: "rev-2",
    tradeId: "tr-past-2",
    fromUserId: "user-3",
    fromUserName: "Camila García",
    toUserId: "user-1",
    rating: 5,
    comment: "Todo perfecto, muy recomendable para hacer intercambios en la comunidad.",
    date: "2024-01-28T14:30:00.000Z",
    bookTitle: "Cosmos",
  },
  {
    id: "rev-3",
    tradeId: "tr-past-3",
    fromUserId: "user-1",
    fromUserName: "Franco Papa",
    toUserId: "user-2",
    rating: 5,
    comment: "Puntual y el ejemplar tal cual lo descripto en la publicación. ¡Muchas gracias!",
    date: "2024-01-22T11:00:00.000Z",
    bookTitle: "Ficciones",
  },
]

export const SEED_POINT_MOVEMENTS: PointMovement[] = [
  {
    id: "pm-1",
    userId: "user-1",
    type: "INICIAL",
    amount: 100,
    balanceAfter: 100,
    description: "Bienvenida a Mercado Libro — Puntos iniciales otorgados al registrarse",
    date: "2024-01-10T10:00:00.000Z",
  },
  {
    id: "pm-2",
    userId: "user-2",
    type: "INICIAL",
    amount: 100,
    balanceAfter: 100,
    description: "Puntos iniciales de registro",
    date: "2023-11-15T12:00:00.000Z",
  },
  {
    id: "pm-3",
    userId: "user-2",
    type: "BONO_INTERCAMBIO",
    amount: 40,
    balanceAfter: 140,
    description: "Puntos acreditados por intercambios exitosos completados",
    date: "2024-01-20T16:00:00.000Z",
  },
]

export const SEED_TRADES: TradeRequest[] = [
  {
    id: "trade-init-1",
    type: "PUNTOS",
    status: "PENDIENTE",
    requestedBookId: "book-1",
    requesterId: "user-2",
    requesterName: "Miguel Bartesaghi",
    ownerId: "user-1",
    ownerName: "Franco Papa",
    points: 50,
    createdAt: "2024-02-11T12:00:00.000Z",
    updatedAt: "2024-02-11T12:00:00.000Z",
  },
]

export const SEED_TRACKED: TrackedBook[] = [
  {
    id: "track-1",
    userId: "user-1",
    title: "Ficciones",
    author: "Jorge Luis Borges",
    category: "Ficción",
    maxPoints: 70,
    acceptableConditions: ["Nuevo", "Como nuevo", "Muy bueno"],
    privateNotes: "Edición preferentemente tapa blanda para llevar en viajes.",
    createdAt: "2024-02-01T10:00:00.000Z",
  },
  {
    id: "track-2",
    userId: "user-1",
    title: "El túnel",
    author: "Ernesto Sabato",
    category: "Ficción",
    maxPoints: 45,
    acceptableConditions: ["Como nuevo", "Muy bueno", "Bueno"],
    privateNotes: "Buscando para regalar.",
    createdAt: "2024-02-05T12:00:00.000Z",
  },
]

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    userId: "user-1",
    type: "TRADE_REQUEST",
    title: "Nueva solicitud de intercambio",
    message: "Miguel Bartesaghi solicitó tu libro 'Rayuela' por 50 puntos.",
    read: false,
    date: "2024-02-11T12:00:00.000Z",
    linkScreen: "intercambios",
    linkData: { tradeId: "trade-init-1", bookId: "book-1" },
  },
  {
    id: "notif-2",
    userId: "user-1",
    type: "TRACKER_MATCH",
    title: "¡Libro de tu tracker disponible!",
    message: "Se publicó 'Ficciones' de Jorge Luis Borges a 65 pts (dentro de tu criterio de 70 pts).",
    read: true,
    date: "2024-02-02T12:05:00.000Z",
    linkScreen: "inicio",
    linkData: { bookId: "book-2" },
  },
]
