package com.ingenieriaSoftware2.Enums;

public enum CategoriaLibro {
    FICCION_GENERAL,
    CIENCIA_FICCION,
    FANTASIA,
    MISTERIO_Y_THRILLER,
    ROMANCE,
    TERROR_Y_SUSPENSO,
    NOVELA_HISTORICA,
    POESIA_Y_DRAMA,
    BIOGRAFIAS,
    HISTORIA,
    CIENCIA_Y_TECNOLOGIA,
    POLITICA,
    AUTOAYUDA_Y_DESARROLLO_PERSONAL,
    NEGOCIOS_Y_FINANZAS,
    SALUD,
    COCINA,
    INFANTIL,
    JUVENIL,
    COMIC,
    ACADEMICO,
    IDIOMAS,
    OTROS
}
